{% set name = "libpgmath" %}
{% set version = "2021.08.06" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/flang-compiler/flang/archive/95937565e4d111dccc4e7bd422dc43e7cd70d193.tar.gz
  sha256: 122e971c9e6f371172c7fc222037edfbcc02a63ef26f815416f6207af43c0f0c

build:
  number: 0
  skip: True  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage("libpgmath", max_pin="x.x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python
    - pip
    - clangxx     # [not osx]
    - llvm-tools  # [not osx]
    # TODO: Fix the lit conda package on windows
    # - lit
    - jom        # [win]
    - posix      # [win]
    - m2-make    # [win]
    - cmake
  host:
    - clangxx   # [osx]

test:
  commands:
    - test -f "${PREFIX}/lib/libpgmath${SHLIB_EXT}"         # [unix]
    - test -f "${PREFIX}/lib/libpgmath.a"                   # [unix]
    - if not exist "%LIBRARY_BIN%\pgmath.dll" exit 1        # [win]
    - if not exist "%LIBRARY_LIB%\pgmath.lib" exit 1        # [win]
    - if not exist "%LIBRARY_LIB%\libpgmath.lib" exit 1     # [win]

about:
  home: http://github.com/flang-compiler/flang
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: 'Math library for flang runtime'

extra:
  recipe-maintainers:
    - isuruf
