travis:
  secure:
    BINSTAR_TOKEN: RsSxAlaGnDpqaql5LFa8VM3c+EefKV+lLz9Vhw3DIRStPHPgOvhpX+xOrvmdPxDduVlmoS5jjzdu0eGM0IEVA6OhXnHhKttY7gjnb9c5/2Mi5LRZMqy+nY+s2D3RIC2lGDJ6rtKTSUKA9uOu8YD62aPyiAz0Kajn/fq7zVgNAs5lpM3KkcsisA00kYlKWSBS7QHeHGexZWjm++npdrefgaqjZVPLxYM9GmZpybmWi9mb+NEXhvWoi+c8f8uxmKNfvPw05GMj7GlFof3rX6/SxX5/dJ/pAdOb4W+x693YZD3OOeTWLVxk+yFTby1x0SoGA4lx0Ld0/gA8Aywqqqs4xCVIPMBBaTm8+bdXpB+4UPbtEXYDfLluq8IuAx4WoWgWujZIAs7mu0ecOYQmykTgRXkznoZ3E4z0wc5XSkUNr9nMLyIHq07kGAJ8yQhRcHnWRaKL9zQbSD+lkIF6uCTLQA5kkypka9TI1ein7MV/qhi2L8jqPCdFmhYtcHta2l31lBSGFIKSNcShvexQrDW7u/gp7cq7W0CP4HpD/pnN0ySY/Ht0R5HYFfSEiKiQr7+oohpKDmLKsQhCfEnSMA2VgxP/7XRspa6buj5Lv0XwfDgAczmBUrBy+DL5E3Zqq64noHimVws9X5CH5hQGLZCZJKtb2d3xHlQtQ3P4lhomSHE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
